### ISSUE TITLE
What is the reason for the jump in the predicted values of the fifth axis and the sixth axis？

### ISSUE THREAD

**Issue by cuggx** [shamilmamedov/dynamic_calibration#10]
hi， what is the reason for the jump in the predicted values of the fifth axis and the sixth axis？
![B@}HTS) )B7)SUQFNB 46UE](https://user-images.githubusercontent.com/100672486/166694858-a04a83cd-4a2a-4c4d-bbd4-6f3e9539f0fa.png)

**Comment by shamilmamedov** [comment]
Hi!
I guess, the reason is the sign change of the velocity of the sixth joint, that results in sudden change in Coulomb friction. To verify this hypothesis I would plot velocity under the torque figure, and also torque due to Coulomb friction.

**Comment by cuggx** [comment]
Thanks！ I have another question. The robot's inertia parameters and centroid position are in the automatically generated file, can I know exactly?

**Comment by shamilmamedov** [comment]
They are parsed from the URDF file

**Comment by cuggx** [comment]
I get it, thanks！
