### ISSUE TITLE
Which reference coordinate system is the inertia tensor I in "tau = Ypi"? Centroid coordinate or link coordinate?

### ISSUE THREAD

**Issue by Nnboy** [shamilmamedov/dynamic_calibration#12]
Thank you very much for your work. I have some questions about some details.

I can use ‘generate_rb_regressor(path_to_urdf);’ to generate regression matrix. But in formula $tau=Y (q, dq, ddq) pi$, I don't know in which reference coordinate the inertia tensor $I$ is expressed. Centroid coordinate  or link coordinate ?

**Comment by shamilmamedov** [comment]
Hi @Nnboy. I am glad that you find my work useful. 

In regressor form of the inverse dynamics, the inertia tensor is always expressed in the link coordinate frame (that is attached to the beginning of the link -- just after the joint).
