### ISSUE TITLE
A question about "generate_rb_dynamics.m"

### ISSUE THREAD

**Issue by MuziYT** [shamilmamedov/dynamic_calibration#13]
Thanks for your work, it helps me a lot. Now, I have modified the code and hope it can be applied to any degree of freedom manipulator. First, I tried to apply it in a 7DOF manipulator, whose urdf file was generated by myself. I am currently facing two issues and would like to seek your advice
1. Regressor was generated by "generate_rb_regressor.m", when run "test_rb_inverse_dynamics.m", I found that the value of  "norm(tau_matlab - tau_reg)"  is about 0.003, bigger than 1e-08, does it reasonable? 
2. When I run "experiment_design.m", the program has been running for about 14 hours and still hasn't ended. My cpu is "core i9 12900K". I think there may be some issues with the process of generating my regressor.
So ,can you help me, thank you a lot.

**Comment by Sunday377** [comment]
In my opinion, it is not appropriate to use the Lagrange method for 7 degrees of freedom robotic arms

**Comment by FelixvanZ** [comment]
Hey! Have you solved this problem, I am facing the same one. How did you solve it? Is it caused by using the Lagrangian method for a 7 DoF manipulator?

**Comment by shamilmamedov** [comment]
Hi guys, 

Lagrange method can be used for any degrees of freedom robot, it's very generic method. Trust me on this, I have used it for 7 DoF robot, just make sure your URDF is correct and that it's parsed correctly.

**Comment by shamilmamedov** [comment]
> Thanks for your work, it helps me a lot. Now, I have modified the code and hope it can be applied to any degree of freedom manipulator. First, I tried to apply it in a 7DOF manipulator, whose urdf file was generated by myself. I am currently facing two issues and would like to seek your advice
> 
>     1. Regressor was generated by "generate_rb_regressor.m", when run "test_rb_inverse_dynamics.m", I found that the value of  "norm(tau_matlab - tau_reg)"  is about 0.003, bigger than 1e-08, does it reasonable?
> 
>     2. When I run "experiment_design.m", the program has been running for about 14 hours and still hasn't ended. My cpu is "core i9 12900K". I think there may be some issues with the process of generating my regressor.
>        So ,can you help me, thank you a lot.

1. It's reasonable to have 0.003. Don't worry about it. If regressor is wrong then errors are gonna be much larger. 
2. Experiment design and regressor generation can take many hours. Be patient; try few different seeds for experiment design. 

Nowadays there are great libraries that would allow you to get regressor numerically instead of symbolically, such as Pinocchio. I would definitely try it out.

**Comment by MuziYT** [comment]
Thanks for your help！



---- Replied Message ----
| From | Shamil ***@***.***> |
| Date | 09/26/2024 20:15 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [shamilmamedov/dynamic_calibration] A question about "generate_rb_dynamics.m" (Issue #13) |

Thanks for your work, it helps me a lot. Now, I have modified the code and hope it can be applied to any degree of freedom manipulator. First, I tried to apply it in a 7DOF manipulator, whose urdf file was generated by myself. I am currently facing two issues and would like to seek your advice

1. Regressor was generated by "generate_rb_regressor.m", when run "test_rb_inverse_dynamics.m", I found that the value of  "norm(tau_matlab - tau_reg)"  is about 0.003, bigger than 1e-08, does it reasonable?

2. When I run "experiment_design.m", the program has been running for about 14 hours and still hasn't ended. My cpu is "core i9 12900K". I think there may be some issues with the process of generating my regressor.
   So ,can you help me, thank you a lot.

It's reasonable to have 0.003. Don't worry about it. If regressor is wrong then errors are gonna be much larger.
Experiment design and regressor generation can take many hours. Be patient; try few different seeds for experiment design.

Nowadays there are great libraries that would allow you to get regressor numerically instead of symbolically, such as Pinocchio. I would definitely try it out.
