### ISSUE TITLE
ttributeError: 'SLSQP' object has no attribute 'h_start'

### ISSUE THREAD

**Issue by Sunday377** [shamilmamedov/dynamic_calibration#14]
![6a70d2cffacf0789d3160b42d6360aa8](https://github.com/shamilmamedov/dynamic_calibration/assets/74995767/2bb2ba17-4e03-4513-a61b-1e78a5dfc2c4)

**Comment by Sunday377** [comment]
the version of pyOpt is 1.2.0

**Comment by shamilmamedov** [comment]
Can you give more context?
