### ISSUE TITLE
Can you tell me which book or article do you reference about the screw dynamic 

### ISSUE THREAD

**Issue by dbdxnuliba** [shamilmamedov/dynamic_calibration#2]
Can you tell me which book or article do you reference about the screw dynamic  thanks

**Comment by shamilmamedov** [comment]
Sure, G.  Garofalo,  C.  Ott,  and  A.  Albu-Sch ̈affer,  “On  the  closed  form  computation  of  the  dy-namic matrices and their differentiations,” in2013  IEEE/RSJ  International  Conference  onIntelligent Robots and Systems, pp. 2364–2359, IEEE, 2013

**Comment by dbdxnuliba** [comment]
thanks a lot
