### ISSUE TITLE
Which book or paper does your code refer to？

### ISSUE THREAD

**Issue by QNjeason** [shamilmamedov/dynamic_calibration#3]
I want to know in detail how to use your code, thank you

**Comment by shamilmamedov** [comment]
It depends on your robot. First of all, you should have URDF of your robot. Then you run ur_regressors_lgr.m to obtain regressor matrix as well as dynamics matrices in symbolic form with subsequent generation of functions. 

If you need to obtain base parameters (minimal number of parameters) then you run ur_base_params_QRlgr.m.

If you need to do trajectory planning for identification then you run ur_exprmt_dsgn.m.

For processing the data from the robot you can use filterData.m.

What exactly for do you want to use this code?

**Comment by QNjeason** [comment]
I want to realize the parameter identification of my robot, which is similar to ur robot.
Thank a lot for you reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shamil Mamedov"<notifications@github.com&gt;; 
发送时间: 2020年6月19日(星期五) 晚上7:36
收件人: "shamilmamedov/dynamic_calibration"<dynamic_calibration@noreply.github.com&gt;; 
抄送: "何湘粤"<1309082105@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shamilmamedov/dynamic_calibration] Which book or paper does your code refer to？ (#3)





 
It depends on your robot. First of all, you should have URDF of your robot. Then you run ur_regressors_lgr.m to obtain regressor matrix as well as dynamics matrices in symbolic form with subsequent generation of functions.
 
If you need to obtain base parameters (minimal number of parameters) then you run ur_base_params_QRlgr.m.
 
If you need to do trajectory planning for identification then you run ur_exprmt_dsgn.m.
 
For processing the data from the robot you can use filterData.m.
 
What exactly for do you want to use this code?

**Comment by shamilmamedov** [comment]
I see. Can you measure motor torques or only currents?

**Comment by QNjeason** [comment]
At present, only current can be measured.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shamil Mamedov"<notifications@github.com&gt;; 
发送时间: 2020年6月19日(星期五) 晚上8:57
收件人: "shamilmamedov/dynamic_calibration"<dynamic_calibration@noreply.github.com&gt;; 
抄送: "何湘粤"<1309082105@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shamilmamedov/dynamic_calibration] Which book or paper does your code refer to？ (#3)





 
I see. Can you measure motor torques or only currents?

**Comment by shamilmamedov** [comment]
It really complicates the identification. Try to get the coefficient between the current and torque (tau = K*i). 

If it is impossible, then you need to do extra experiment with a payload. You need to know at least one dynamic parameter of the load, for example mass. Here is a paper you can use
Gautier, Maxime, and Sébastien Briot. "Global identification of joint drive gains and dynamic parameters of robots." Journal of Dynamic Systems, Measurement, and Control 136.5 (2014).

For identification good references are Handbook of robotics and a recent paper on the topic
Sousa, Cristóvão D., and Rui Cortesao. "Physical feasibility of robot base inertial parameter identification: A linear matrix inequality approach." The International Journal of Robotics Research 33.6 (2014): 931-944.

**Comment by QNjeason** [comment]
Thank you for your reply. I will try to implement and read your recommended references.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shamil Mamedov"<notifications@github.com&gt;; 
发送时间: 2020年6月25日(星期四) 中午1:20
收件人: "shamilmamedov/dynamic_calibration"<dynamic_calibration@noreply.github.com&gt;; 
抄送: "何湘粤"<1309082105@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shamilmamedov/dynamic_calibration] Which book or paper does your code refer to？ (#3)





 
It really complicates the identification. Try to get the coefficient between the current and torque (tau = K*i).
 
If it is impossible, then you need to do extra experiment with a payload. You need to know at least one dynamic parameter of the load, for example mass. Here is a paper you can use
 Gautier, Maxime, and Sébastien Briot. "Global identification of joint drive gains and dynamic parameters of robots." Journal of Dynamic Systems, Measurement, and Control 136.5 (2014).
 
For identification good references are Handbook of robotics and a recent paper on the topic
 Sousa, Cristóvão D., and Rui Cortesao. "Physical feasibility of robot base inertial parameter identification: A linear matrix inequality approach." The International Journal of Robotics Research 33.6 (2014): 931-944.

**Comment by QNjeason** [comment]
Hello!
How to generate the m file of Autogen folder?
Can you give me some instructions?
Thank you.

**Comment by shamilmamedov** [comment]
Hi. 
The content of the Autogen folder is generated from ur_regressors_lgr.m which uses parsed URDF file of the robot. Just go through the file.

**Comment by QNjeason** [comment]
Thank you for your reply.
Let me take a look at the m file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shamil Mamedov"<notifications@github.com&gt;; 
发送时间: 2020年7月9日(星期四) 晚上7:43
收件人: "shamilmamedov/dynamic_calibration"<dynamic_calibration@noreply.github.com&gt;; 
抄送: "何湘粤"<1309082105@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shamilmamedov/dynamic_calibration] Which book or paper does your code refer to？ (#3)





 
Hi.
 The content of the Autogen folder is generated from ur_regressors_lgr.m which uses parsed URDF file of the robot. Just go through the file.

**Comment by QNjeason** [comment]
Hello, Mr. Shami
      I encountered the following problems when running the simulation, please guide me, thank you.
**When I run ur_idntfcn_frcn.m code, I have the following errors.**
![image](https://user-images.githubusercontent.com/52246049/87143643-02452880-c2d9-11ea-9482-901aafe1339d.png)
**When I run ur_vldtn.m code, I have the following errors.**
![image](https://user-images.githubusercontent.com/52246049/87143789-47695a80-c2d9-11ea-96f2-f5149319d87a.png)
**When I run ur_idntfcn_real.m code, I have the following errors.**
![image](https://user-images.githubusercontent.com/52246049/87143864-6bc53700-c2d9-11ea-9ced-b14fdf6be4ce.png)
**When I run ur_idntfcn_drvgns.m code, I have the following errors.**
![image](https://user-images.githubusercontent.com/52246049/87143907-7c75ad00-c2d9-11ea-8d88-0fd0c4f874f9.png)

**Comment by shamilmamedov** [comment]
ur_idntfcn_frcn is used to perform identification of nonlinear friction model of each joint, at first you don't need it, because usually linear friction model works fine

before validation you need to run ur_idntfcn_real.m to identify parameters

the last screenshot looks weird, it shouldn't happen. If you do everything for your own model, then after deriving regressor matrix you need to perform parameter reduction (QR decomposition) ur_base_params_QRlgr.m. Then everything should work fine

**Comment by QNjeason** [comment]
I download these codes from your GitHub again, but I still can't get the solution when running on MATLAB.You can try it on your computer to see if it fails. motorDynamicsIncluded=1.If motordynamicsincluded = 0, ur cannot run normally_ idntfcn_ drvgns.m
![image](https://user-images.githubusercontent.com/52246049/87510247-ca0d6380-c6a5-11ea-8e1c-1af734309799.png)
![image](https://user-images.githubusercontent.com/52246049/87510442-2f615480-c6a6-11ea-9760-4b5f0e52568e.png)

**Comment by gaodada555** [comment]
Hi,  is it good for pratical use? do you have test  in a real robot? than you!

**Comment by gaodada555** [comment]
Can you tell me the email address for further contact？ thanks.

**Comment by shamilmamedov** [comment]
Hi, yes the code has been used for offline identification of UR10E.

**Comment by shamilmamedov** [comment]
if you have specific questions, ask them here, maybe there are other people interested in the same questions

**Comment by 2743701314** [comment]
![image](https://user-images.githubusercontent.com/46472203/111854844-5c17eb00-895c-11eb-910a-f21021e78fe4.png)

![image](https://user-images.githubusercontent.com/46472203/111854817-44406700-895c-11eb-9719-47d7e65d0166.png)
How do I generate this value.m

**Comment by shamilmamedov** [comment]
> ![image](https://user-images.githubusercontent.com/46472203/111854844-5c17eb00-895c-11eb-910a-f21021e78fe4.png)
> 
> ![image](https://user-images.githubusercontent.com/46472203/111854817-44406700-895c-11eb-9719-47d7e65d0166.png)
> How do I generate this value.m

You don't need to generate anything. The function is YALMIP overload, so if you have YALMIP installed _value_  function will give you the numerical values of the optimization variable

**Comment by 2743701314** [comment]
Thanks to the guidance, I've solved that problem.
Now I have a new question to ask you. Which paper can you find this linear friction-free model in?
![image](https://user-images.githubusercontent.com/46472203/112161681-5523fd80-8c26-11eb-8c2c-d1caeb341bdc.png)

**Comment by shamilmamedov** [comment]
> Thanks to the guidance, I've solved that problem.
> Now I have a new question to ask you. Which paper can you find this linear friction-free model in?
> ![image](https://user-images.githubusercontent.com/46472203/112161681-5523fd80-8c26-11eb-8c2c-d1caeb341bdc.png)

You are welcome! This particular friction model was taken from [this](http://www.diag.uniroma1.it//~labrob/pub/papers/Mechatronics_Feb2018.pdf) paper

**Comment by 2743701314** [comment]
Thank you very much

**Comment by wzzz9** [comment]
What method is the dynamics based on?Newton - Euler or Lagrange?

**Comment by 2743701314** [comment]
> What method is the dynamics based on?Newton - Euler or Lagrange?

Lagrange

**Comment by 2743701314** [comment]
Hello, how to solve this problem?Thank you
ur_idntfcn_frcn.m
![image](https://user-images.githubusercontent.com/46472203/113147398-51662b80-9263-11eb-877f-c3bffa04f652.png)
![image](https://user-images.githubusercontent.com/46472203/113147471-62af3800-9263-11eb-82e6-754f54f505b4.png)
