### ISSUE TITLE
Could you tell me which book or article do you reference about the physical feasibility?

### ISSUE THREAD

**Issue by zhangfunning** [shamilmamedov/dynamic_calibration#5]

**Comment by shamilmamedov** [comment]
There are several papers on that topic:

1. Sousa, Cristóvão D., and Rui Cortesao. "Physical feasibility of robot base inertial parameter identification: A linear matrix inequality approach." The International Journal of Robotics Research 33.6 (2014): 931-944.
2. Sousa, Cristóvão D., and Rui Cortesao. "Inertia tensor properties in robot dynamics identification: A linear matrix inequality approach." IEEE/ASME Transactions on Mechatronics 24.1 (2019): 406-411.
3. Wensing, Patrick M., Sangbae Kim, and Jean-Jacques E. Slotine. "Linear matrix inequalities for physically consistent inertial parameter identification: A statistical perspective on the mass distribution." IEEE Robotics and Automation Letters 3.1 (2017): 60-67.
