### ISSUE TITLE
Error in experiment_design.m

### ISSUE THREAD

**Issue by Nnboy** [shamilmamedov/dynamic_calibration#6]
Hello! When I run this code [ `experiment_design.m`](https://github.com/shamilmamedov/dynamic_calibration/blob/master/experiment_design.m) the following error appears.

```matlab
>> experiment_design
Unrecognized function or variable 'a'.
Error in experiment_design (line 66)
    x0 = reshape([a b], [6*2*traj_par.N, 1]);  
```
https://github.com/shamilmamedov/dynamic_calibration/blob/174ccbd315d3fddd8d56c6c44c3c579e19ce3d0c/experiment_design.m#L66
Should I do something before running this code? thank you for your reply

**Comment by shamilmamedov** [comment]
Hello @Nnboy! Line 66 shouldn't be there.  You can remove it yourself or pull the last version of the master branch.

**Comment by Nnboy** [comment]
@shamilmamedov .Thanks for your reply! I remove the line 66, it works. I saw that you modified the code, but it seems that you only need to delete the 66th line of code. The variables related to the joint restriction are still used in the following lines of code.
