### ISSUE TITLE
When I run the function main.m, the following error occurred

### ISSUE THREAD

**Issue by zhangpeng1221** [shamilmamedov/dynamic_calibration#7]
Hello! When I run the function main.m, the following error occurred. Could you please tell me how to solve it? Looking forward to your reply.
错误使用  -  (line 44)
Adding NaN to an SDPVAR makes no sense.

出错 estimate_dynamic_params>physicallyConsistentEstimation (line 157)
    obj = norm(Tau - Wb*[pi_b; pi_frctn]);

出错 estimate_dynamic_params (line 49)
    [sol.pi_b, sol.pi_fr, sol.pi_s] =
    physicallyConsistentEstimation(Tau, Wb, baseQR);

出错 main (line 40)
sol = estimate_dynamic_params(path_to_est_data, idxs, ...

**Comment by shamilmamedov** [comment]
Hi! You need to install YALMIP and SPDPT3

**Comment by zhangpeng1221** [comment]
> Hi! You need to install YALMIP and SPDPT3

Thank you very much for your reply. In fact, I have already installed YALMIP and SPDPT3. Maybe something went wrong in some process, so I will check again. Thanks again for your answer

**Comment by shamilmamedov** [comment]
I can run main.m without any problem. Have you changed anything in the code? Have you tried to run YALMIP tests?

**Comment by zhangpeng1221** [comment]
> I can run main.m without any problem. Have you changed anything in the code? Have you tried to run YALMIP tests?

I did have a problem with YALMIP. Thank you very much for your reminder, I solved it.I can run main.m finally

**Comment by ryan-bzr** [comment]
> Hello! When I run the function main.m, the following error occurred. Could you please tell me how to solve it? Looking forward to your reply. 错误使用 - (line 44) Adding NaN to an SDPVAR makes no sense.
> 
> 出错 estimate_dynamic_params>physicallyConsistentEstimation (line 157) obj = norm(Tau - Wb*[pi_b; pi_frctn]);
> 
> 出错 estimate_dynamic_params (line 49) [sol.pi_b, sol.pi_fr, sol.pi_s] = physicallyConsistentEstimation(Tau, Wb, baseQR);
> 
> 出错 main (line 40) sol = estimate_dynamic_params(path_to_est_data, idxs, ...

hello，i have the same problem with you. how did you fix your problem with YALMIP? @zhangpeng1221

**Comment by abnerjie** [comment]
Hello, I encountered the same issue: 'Error using - (line 44) Adding NaN to an SDPVAR makes no sense.' Could you please tell me how you resolved it at the time?
